### ISSUE TITLE
User list

### ISSUE THREAD

**Issue by fender** [chrisdew/jsonspace#20]
@chrisdew I'm seeing an issue where the same device and username is able to subscribe to a channel. Is that by design? 
```
data: "{"subscribers":{"channel":"es","list":[{"username":"BQlAEERtq4","extra":{"displayName":"Fenda me","language":"es","ability":"advanced","items":["base_avatar_yellow"],"abilities":{"beginner":false,"intermediate":false,"advanced":true},"topic":"random"}}]}}"
```

I don't know how the server got into this state but I have noticed it multiple times. On my client I go through the following steps.

1. Watch channel
2. If the current user is already in the list of subscribers, immediately subscribe to the channel. I do this because if the user restarted the app or reconnected to the internet they may need to re-subscribe. This also created issue #18 
3. After subscribing again, if I then send an unsubscribe for the current username and channel it doesn't seem to get sent at all to other clients. So we end up with multiple users in the subscriber list that. At least I think this is the cause of the issue.

Is each subscription being counted as a separate connection? Again, this may be by design but it's causing issues.

**Comment by chrisdew** [comment]
Multiple subscriptions to the same channel, as the same user on the same websocket has not been disallowed.  It's not a decision, just something which hasn't been ruled out, because why would the client ever do it?  But is seems that they are, so we need to fix it.

The subscriber will get multiple copies of published messages, if they are subscribed to the same channel multiple times.

Do you want me to make it so that attempts to subscribe to a ws/user/channel combo, which is already subscribed, should be ignored?  

Is it OK for updated "extra" to be ignored?

**Comment by chrisdew** [comment]
@fender - see above.

**Comment by fender** [comment]
@chrisdew So the problem is that a client can disconnect from the internet whilst being subscribed to a channel. The server doesn't issue a timeout immediately (so considers them as still subscribed). The client may bring back internet connection within a few seconds of dropping before and when will re-subscribe to the channel automatically.

So at first I am thinking each user should only be allowed a single user subscription to a channel. But if we add in multiple devices to the mix then it could get tricky. Can we say one device/user combo per channel?

**Comment by chrisdew** [comment]
There are several concerning things in your comment above.

> The server doesn't issue a time out immediately (so considers them as still subscribed).

Are you implying that a time out unsubscribes a user from a channel - I had previously understood it to just be an informational thing.  

What are the exact semantics of a time out?  
- Does it cause an unsubscribe?  To all channels?
- Does it close the user's websocket connections?

> But if we add in multiple devices to the mix then it could get tricky.

We currently have no concept of "device" in pubsub, we have users and we have websocket connections.  

This would be major work and has a lot of problems.  Just to start:
- Are devices just a name for client network addresses?
- If so, how to we handle phones with both wifi and 3G addresses (nearly all of them)?

**Comment by chrisdew** [comment]
Sorry, I'm being a bit slow.  After re-reading a few times I still can't understand what the original issue is.

Could you post the full comms logs from the browser tabs where you demonstrate the issue?

Do you get the same result when testing against a single server on your machine, as opposed to using the Linode machines?  i.e. is it a replication bug.

**Comment by chrisdew** [comment]
Ah, I think I see what the issue is. Is this about stale connections keeping the user subscribed as the server doesn't know the connection has been silently broken on the client end, or by nat or flaky networks?

I have a couple of solutions in mind.  The worst is a frequent server originated ping, which would cause broken connections to fail in a few seconds, rather than remaining stale.

My earlier question, about the semantics of a timeout, still stands.

**Comment by chrisdew** [comment]
Would this work?

A new request: 

{"unique_connection":{"device":"<imei or uuid>"}}

This would cause the server to close (and therefore unsubscribe) all websocket connections which had previously sent that request with the same value for "device".

No frequent pinging from the server would be required.

Time out question still stands.

**Comment by fender** [comment]
@chrisdew I think we (or me) may be overcomplicating things. It all boils down to the username being unique in subscriber lists. There should never be 2 or more of the same username in the list. If multiple websockets are opened with the same username, thats fine, they all receive messages for the user. Make sense?

**Comment by chrisdew** [comment]
Hi Joe,

I disagree, if the user has an app open on two different devices (phone and
tablet, or phone and web, for example) it is *required* that a username may
be used to subscribe to a channel from more than one websocket connection.

Otherwise the system would get swamped with device A kicking device B out
and vice-versa, forever, many times per second.

Now that I have had time to consider it further, it seems like a
"unique_connection" message solves the stale connection issue nicely, and
at the right level of abstraction (at the connection level, rather than at
the application level).  It will also work well for phones where internet
access is bouncing between GPRS and Wifi.

All the best,

Chris.

@chrisdew <https://github.com/chrisdew> I think we (or me) may be
overcomplicating things. It all boils down to the username being unique in
subscriber lists. There should never be 2 or more of the same username in
the list. If multiple websockets are opened with the same username, thats
fine, they all receive messages for the user. Make sense?

—
Reply to this email directly or view it on GitHub
<https://github.com/chrisdew/jsonspace/issues/20#issuecomment-181406557>.

**Comment by fender** [comment]
I'm not sure how you've implemented subscriber lists but my hope was that
it's abstracted from connections. So that it's just an array of
unique usernames. We don't store which websocket connection is the one
subscribed. If there is 10 connections that all sent the subscribe message
for the same channel and username then we only have 1 entry for that
username in the subscriber list. When a message is sent to the channel, the
server looks for all connections with the usernames in the channel and
broadcasts to them.

I feel like this is the simplest solution.

**Comment by chrisdew** [comment]
Ironically, we've got a bit of a communication problem.

> I'm not sure how you've implemented subscriber lists but my hope was that
it's abstracted from connections.
Yes, connections and subscriptions are separate bits of data.

> We don't store which websocket connection is the one subscribed.
Pubsub does store which websocket it is, for each subscription.  This is
how published messages are distributed.

> When a message is sent to the channel, the server looks for all
connections with the usernames in the channel and broadcasts to them.
No, when a message is sent to a channel, the server looks for all
subscriptions to that channel, and sends to the websocket associated with
each subscription.  When a websocket closes, all of its subscriptions are
removed (via unsubscribe objects).  "Subscribed" messages (the "d" is
important" are sent to the channel's subscribers and watchers only when the
number of subscriptions goes from 0 to 1.  Likewise "unsubscribed" messages
are only sent when the number of subscriptions goes from 1 to 0.

Usernames are a property of subscriptions (and of watches and of
publishes).

Usernames are *not* a property of websocket connections.  There is no
"login" message, or similar.

(By coincidence, not by requirement or design, multiple usernames can be
used concurrently on a single websocket. This is not something you need
now, but may be useful later.)

Have a look at the messages sent and received by the test client.

The system is designed to allow independent sets of watches/subscriptions
from the same user on different connections (from different devices).

Have you noticed that subscriptions are a property of websocket
connections, as well of of users and channels?  Subscriptions made on one
websocket do not affect other websockets.

*I think this all revolves around how we want multiple devices (with the
same user/username) to be treated. * (Devices include web apps, too, where
each tab, or browser, is a separate device)

Do you agree that this is the principle point of our differing
understanding?

System A.

With the current code, each device is free to watch and subscribe to
channels *independently* of other connections/devices used by the same
user.  Whenever its connection is broken, a device reconnects and
rewatches/resubscribes based on *local device state*.

The proposed "unique_connections" is just an efficient way of closing stale
connection from the same device (of a phone which switched from GPRS to
Wifi, for example), and by consequence, removing the stale subscriptions.

System B.

With your understanding, I think, that you think, that subscriptions are
properties of users and channels, not of users, channels and connections.
Have I understood correctly?

This leads to the situation where multiple devices will always be watching
and subscribed to the *same* set of channels, if the same username.

This then requires that the devices keep their app-state in sync otherwise
you get devices receiving messages from channels that they don't think
they're subscribed to.

This is a huge ball of complexity that I want to keep the apps away from.

Have I correctly understood how you thought that the server worked (System
B)?

Do you already have a solution for keeping a user's multiple devices, in
lock-step?  Is that what your users want?

I believe that in most apps, a user will expect to be able to subscribe to
#channel_0 on their phone and #channel_1 on their ipad, independently.  How
would the ipad handle receiving messages on #channel_0, to which it doesn't
think it has subscribed?

*I won't make any changes in the next few days, while we think about, and
discuss, this. *

A change to System B, if the multi-device issues can be ironed out, would
take many hours (mostly in rewriting all of the tests).  I would need to be
really sure that System B is a sound design (for multiple devices) in order
to follow this path.

I'm not sure how you've implemented subscriber lists but my hope was that
it's abstracted from connections. So that it's just an array of
unique usernames. We don't store which websocket connection is the one
subscribed. If there is 10 connections that all sent the subscribe message
for the same channel and username then we only have 1 entry for that
username in the subscriber list. When a message is sent to the channel, the
server looks for all connections with the usernames in the channel and
broadcasts to them.

I feel like this is the simplest solution.

On Wednesday, February 10, 2016, Chris Dew <notifications@github.com> wrote:

> Hi Joe,
>
> I disagree, if the user has an app open on two different devices (phone
and
> tablet, or phone and web, for example) it is *required* that a username
may
> be used to subscribe to a channel from more than one websocket connection.
>
> Otherwise the system would get swamped with device A kicking device B out
> and vice-versa, forever, many times per second.
>
> Now that I have had time to consider it further, it seems like a
> "unique_connection" message solves the stale connection issue nicely, and
> at the right level of abstraction (at the connection level, rather than at
> the application level). It will also work well for phones where internet
> access is bouncing between GPRS and Wifi.
>
> All the best,
>
> Chris.
>
> @chrisdew <https://github.com/chrisdew> I think we (or me) may be
> overcomplicating things. It all boils down to the username being unique in
> subscriber lists. There should never be 2 or more of the same username in
> the list. If multiple websockets are opened with the same username, thats
> fine, they all receive messages for the user. Make sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrisdew/jsonspace/issues/20#issuecomment-181406557>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrisdew/jsonspace/issues/20#issuecomment-182341296>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/chrisdew/jsonspace/issues/20#issuecomment-182399386>.

**Comment by fender** [comment]
Yeah, this is definitely tricky to communicate! I was going to draw up a
flow chart but that didn't really make it much clearer.

I see what you mean regarding the 2 systems. Perhaps we can merge our logic
a bit to land at somewhere like this:

   - Each device watches/subscribes to channels independently of other
   devices. We don't need to keep this state stored between devices.
      - e.g. Joe on iPhone subscribes to channel A, Joe on iPad subscribes
      to channel B. Messages to those channels only get sent to the subscribed
      devices. (A message to channel A is not sent to Joe on iPad)
      - e.g. Joe on iPhone and Joe on iPad subscribe to channel A. Messages
      sent to the channel are sent to both devices.
   - The 'subscribers' list that is sent to other users who watch/subscribe
   to the channel should only ever show a maximum of 1 of each username. Even
   if there are multiple websocket connections with the same username
   subscribed to the channel the list should only show 1.
      - We do this as clients will only use this list to render a list of
      'online users' and so do not want duplicates. I suppose I could make it a
      unique array on the client-side but would prefer this done on the server.
   - "Unsubscribed" message is only sent to all users in a channel when the
   number of connections with the username goes from 1 to 0.
   - You said the "subscribed" message is only sent only when the number of
   connections go from 0 to 1. If we do that then new devices subscribing to a
   channel will not get the list of subscribed users to populate an online
   list. What we really need is do not send the "subscribed" message when a
   connection switches from a "watch" to "subscribe" (i.e. they are already
   watching and then issue a subscribe). That being said, I can probably
   handle all of that client-side so if its easier just to rip this out so
   that "subscribed" is always sent.. go ahead and do that.

How does that sound?

**Comment by chrisdew** [comment]
I'll start with a bit of background - this may appear dogmatic, but it has
helped me create working distributed systems.

"Storing state must be avoided in all circumstances, except those where it
is *absolutely* essential to a component's function."

I originally failed twice with pubsub:

1. PubSub stores the subscriptions (and watches) of connection/username
pairs to channels.  This was unavoidable on two counts, the first is that
published messages need to be sent to the channel's subscribers, and the
second is that it is required for the "presence" information.  i.e. When
the count of a username's subscriptions to a channel go from 0->1 or 1->0.
2. PubSub stores (a limited number of) messages, published on each
channel.  This was unavoidable when delivering a catch-up mechanism.

I then failed a third time when implementing replication:

3. Each PubSub server stores the last heartbeat from each other PubSub
server, so that it knows how to answer DNS queries with only the addresses
of recently operational servers.

Storing state leads to complexity with grows much more quickly that the
number of types of state which are being stored, it's probably a n-squared
thing.

Every bit of stored state is something which must be kept in sync with
other systems.  That is a hard, time-consuming job that I will always seek
to avoid.

Back to what you wrote...

Everything which you wrote is plausible, but the server does not *need* to
know about devices in order to perform it's function.

Here's the first problem I could think of with the server storing
device-related state:

- user_a subscribes to #channel_0 with device_alpha
- device_alpha gets a bit full, user_a uninstalls app
- time passes
- user_a re-installs and runs app
- app creates websocket connection and starts getting messages for
#channel_0, which it is not expecting

I hope you can see that every bit of state is a *potential* liability,
under some circumstances, in a distributed system, and so its inclusion
must be strenuously fought.

(Another case where a similar problem could occur is if the app crashes and
fails to restore its former state on restart.)

"channels a username on a device is subscribed to" is data that is best
*owned* by the running instance of the app on the device.  Putting it on
the server too is just unneeded additional complexity, as now we have two
locations for the same piece of data, which must be kept perfectly in sync.

The proposed "unique_connection" method is not really *part* of System A,
it's more like (as Americans would say) a "band-aid", to get rid of stale
connections without excessive pinging.

I'm perfectly happy to have these design discussions, but I am not
convinced that storing device-related state, on the server, is a good
idea.  While it would be only a bit of work now, it *may* complicate many
more things later, so I don't want it on the server.

Storing device subscriptions on the server seems to be a minor client
convenience at the cost of increased server complexity and risk.

Storing device subscriptions on the server is *not* essential to the server
performing its function.  It can be avoided and so should be avoided.

When writing the documentation, I will emphasise the following:

> Each websocket connection to a PubSub server is independent - it knows
nothing of what was or is being done on other connections, even if these
connections are from the same IP address, app or user.
> Therefore, on *each* successful connection, all "subscribe" and "watch"
messages must be sent anew, as consistent with the application's current
local state.
> Watches and subscriptions are property of connection, username and
channel, not of just of username and channel.  They go away when the
originating connection is broken.
> The "subscribed" message is only sent to clients when the first
subscription for a username/channel pair is made.  Likewise the
"unsubscribed" message is only sent when the last subscription from a
username/channel is removed.

(I think it's time to rename the server->client "subscribed" and
"unsubscribed" messages to "joined" and "left" as they have different
associations (i.e. no dependency on any particular connection) from the
"subscribe" and "unsubscribe" client commands.

Is there anything else I could add to this topic in the documentation to
make it clearer?

Will you accept a "unique_connection" message, as a first solution to the
stale connection problem?

**Comment by fender** [comment]
I'm not suggesting to store device info on the server. Re-read my previous
comment above with that in mind and I think we're on the same page. I
mention devices for the purpose of example but neither the client or server
actually store that info. I don't think we need your suggested band-aid
either.

**Comment by chrisdew** [comment]
Sorry, I misunderstood what you wrote.  I'm very aware that we're looking
at the same interface from opposite sides.  I need a design that works
reliably across a federation of multiple servers distributed across a slow
internet, while you need something which is sane for app developers.

My concerns are all based on what happens when they do A on server_0 and B
on server_1 before server_0 has told server_1 about A.  This all *has* to
be "eventually consistent" (within a few seconds) and that strongly
constrains server design possibilities.

Is what you've suggested functionally equivalent to the following?

The client "subscribe" command gains a new property of "device".  (This
will normally be an IMEI or UUID.)

There can only be one subscription for each combination of (username,
channel, device).

If subscribing would cause the above rule to be violated, the earlier
subscriber is forcibly unsubscribed.

This handles the stale *subscription* problem at the application level
(subscriptions) rather than handling the stale *connection* problem at the
connection level (websockets).

I still don't think that this is the best option, but this is implementable
in a few hours.

If this is in agreement with what you're suggesting, I'll go ahead.  (I may
have misunderstood, all over again.)

I'm not suggesting to store device info on the server. Re-read my previous
comment above with that in mind and I think we're on the same page. I
mention devices for the purpose of example but neither the client or server
actually store that info. I don't think we need your suggested band-aid
either.

On Thursday, February 11, 2016, Chris Dew <notifications@github.com> wrote:

> I'll start with a bit of background - this may appear dogmatic, but it has
> helped me create working distributed systems.
>
> "Storing state must be avoided in all circumstances, except those where it
> is *absolutely* essential to a component's function."
>
> I originally failed twice with pubsub:
>
> 1. PubSub stores the subscriptions (and watches) of connection/username
> pairs to channels. This was unavoidable on two counts, the first is that
> published messages need to be sent to the channel's subscribers, and the
> second is that it is required for the "presence" information. i.e. When
> the count of a username's subscriptions to a channel go from 0->1 or 1->0.
> 2. PubSub stores (a limited number of) messages, published on each
> channel. This was unavoidable when delivering a catch-up mechanism.
>
> I then failed a third time when implementing replication:
>
> 3. Each PubSub server stores the last heartbeat from each other PubSub
> server, so that it knows how to answer DNS queries with only the addresses
> of recently operational servers.
>
> Storing state leads to complexity with grows much more quickly that the
> number of types of state which are being stored, it's probably a n-squared
> thing.
>
> Every bit of stored state is something which must be kept in sync with
> other systems. That is a hard, time-consuming job that I will always seek
> to avoid.
>
> Back to what you wrote...
>
> Everything which you wrote is plausible, but the server does not *need* to
> know about devices in order to perform it's function.
>
> Here's the first problem I could think of with the server storing
> device-related state:
>
> - user_a subscribes to #channel_0 with device_alpha
> - device_alpha gets a bit full, user_a uninstalls app
> - time passes
> - user_a re-installs and runs app
> - app creates websocket connection and starts getting messages for
> #channel_0, which it is not expecting
>
> I hope you can see that every bit of state is a *potential* liability,
> under some circumstances, in a distributed system, and so its inclusion
> must be strenuously fought.
>
> (Another case where a similar problem could occur is if the app crashes
and
> fails to restore its former state on restart.)
>
> "channels a username on a device is subscribed to" is data that is best
> *owned* by the running instance of the app on the device. Putting it on
> the server too is just unneeded additional complexity, as now we have two
> locations for the same piece of data, which must be kept perfectly in
sync.
>
> The proposed "unique_connection" method is not really *part* of System A,
> it's more like (as Americans would say) a "band-aid", to get rid of stale
> connections without excessive pinging.
>
> I'm perfectly happy to have these design discussions, but I am not
> convinced that storing device-related state, on the server, is a good
> idea. While it would be only a bit of work now, it *may* complicate many
> more things later, so I don't want it on the server.
>
> Storing device subscriptions on the server seems to be a minor client
> convenience at the cost of increased server complexity and risk.
>
> Storing device subscriptions on the server is *not* essential to the
server
> performing its function. It can be avoided and so should be avoided.
>
> When writing the documentation, I will emphasise the following:
>
> > Each websocket connection to a PubSub server is independent - it knows
> nothing of what was or is being done on other connections, even if these
> connections are from the same IP address, app or user.
> > Therefore, on *each* successful connection, all "subscribe" and "watch"
> messages must be sent anew, as consistent with the application's current
> local state.
> > Watches and subscriptions are property of connection, username and
> channel, not of just of username and channel. They go away when the
> originating connection is broken.
> > The "subscribed" message is only sent to clients when the first
> subscription for a username/channel pair is made. Likewise the
> "unsubscribed" message is only sent when the last subscription from a
> username/channel is removed.
>
> (I think it's time to rename the server->client "subscribed" and
> "unsubscribed" messages to "joined" and "left" as they have different
> associations (i.e. no dependency on any particular connection) from the
> "subscribe" and "unsubscribe" client commands.
>
> Is there anything else I could add to this topic in the documentation to
> make it clearer?
>
> Will you accept a "unique_connection" message, as a first solution to the
> stale connection problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrisdew/jsonspace/issues/20#issuecomment-182855454>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/chrisdew/jsonspace/issues/20#issuecomment-182886819>.

**Comment by fender** [comment]
Going back to what I wrote, why do we need to send a device ID? If a user
drops net, reconnects and resubscribes then a new connection is made. As
long as the 'subscribers' list doesn't emit duplicates then it's fine. The
old connection will eventually time out right?

**Comment by chrisdew** [comment]
Yes, that's right. I thought that the problem was the delay in the removal
of the first subscription (on the connection which has silently gone
away).

Typically, this delay is 22 minutes, but under some circumstances it can be
indefinite, unless some data is sent to the silently broken connection.

This delay would cause the username to continue to be subscribed to the
channel, after the second connection unsubscribed.

That was what I assumed you were reporting.

Do you think the current design suits your needs?

Is this issue a bug report, just needing a very infrequent ping to identify
and close silently broken connections, rather than a request for system
design change?

**Comment by fender** [comment]
Nope, the only issue is this. When *another* user subscribes to the channel
they get a list of subscribers right? Please just make sure that list only
ever contains a maximum 1 of each username in it. Even if there are 2
connections for the same username subscribed, just makes sure only 1 gets
sent to the other users.

In programmatic terms, just run the 'subscribers' array through a function
to check that each element is unique before sending it to new
watchers/subscribers. That's all it is - nothing more to be done in terms
of dealing with stale connections or whatever.

Does that make sense?

**Comment by chrisdew** [comment]
Ah (lightbulb goes on) it's a bug report about duplicate usernames in
subscriber lists.  Should be straightforward to fix

Sorry for being so slow.  You now know much more about the design than you
ever wanted to know.

**Comment by fender** [comment]
Haha, yeah, that's true. :-) We only needed this so that clients don't
display duplicates in online user lists - although I could have done it
client-side.

**Comment by chrisdew** [comment]
This took ages to replicate - the duplicates only occur if the "extra" is identical for user's subscription on the second connection.

**Comment by fender** [comment]
Ah, right. That's common for my use case though.

**Comment by chrisdew** [comment]
@jfender Can you confirm that you only saw duplicates in when watching, rather than subscribing?
